### ISSUE TITLE
support HTTP over SOCKS5 and ensure compatibility with existing mitmproxy configuration files

### ISSUE THREAD

**Issue by gchuyun** [emanuele-em/proxelar#73]
1、support HTTP over SOCKS5
2、reuse mitmproxy configuration files and certificate

thank you！

**Comment by emanuele-em** [comment]
Hello, sorry for late answer but:
1. SOCKS5 is a functinoality definitely a feature to have, this is not my main project but I try to implement new functionalities from time to time, I think next step might be to split gui and the main functionality and to add a tui. I don't think SOCK5 is super difficult to implement so it will probably one of next improvements.
2. This is not exactly what I want, althought proxelar is strongly inspired by mitmproxy I don't consider it like a clone, however, with last pr I simplified the certificate installation process :)

Thanks for the feedback :)
